[package]
name = "rust_wm"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
env_logger = "0.11.8"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
x11rb = { version = "0.13.2", features = ["cursor"] }
xdg = "3.0.0"
xkeysym = "0.2.1"
