bar_height = 20
spacing = 10
ratio = 0.5
border_size = 1
main_color = "#11111b"
secondary_color = "#74c7ec"

fonts = [
    "-misc-jetbrainsmononl nfp medium-medium-r-normal--20-0-0-0-p-0-iso8859-16",
    "6x13",
    "fixed"
]

# terminal
[[hotkeys]]
modifiers = "CONTROL|MOD"
key = "Return"
action = { Spawn = "alacritty" }

# close window
[[hotkeys]]
modifiers = "MOD"
key = "q"
action = "ExitFocusedWindow"

# quit manager
[[hotkeys]]
modifiers = "CONTROL|MOD"
key = "q"
action = { Spawn = "killall rust_wm" }

# launch app
[[hotkeys]]
modifiers = "MOD"
key = "c"
action = { Spawn = "rofi -show drun" }

# screenshot
[[hotkeys]]
modifiers = "MOD"
key = "u"
action = { Spawn = "maim --select | xclip -selection clipboard -t image/png" }

# tag switch
[[hotkeys]]
modifiers = "MOD"
key = "1"
action = { SwitchTag = 1 }
[[hotkeys]]
modifiers = "MOD"
key = "2"
action = { SwitchTag = 2 }
[[hotkeys]]
modifiers = "MOD"
key = "3"
action = { SwitchTag = 3 }
[[hotkeys]]
modifiers = "MOD"
key = "4"
action = { SwitchTag = 4 }
[[hotkeys]]
modifiers = "MOD"
key = "5"
action = { SwitchTag = 5 }
[[hotkeys]]
modifiers = "MOD"
key = "6"
action = { SwitchTag = 6 }
[[hotkeys]]
modifiers = "MOD"
key = "7"
action = { SwitchTag = 7 }
[[hotkeys]]
modifiers = "MOD"
key = "8"
action = { SwitchTag = 8 }
[[hotkeys]]
modifiers = "MOD"
key = "9"
action = { SwitchTag = 9 }

# move window to tag
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "1"
action = { MoveWindow = 1 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "2"
action = { MoveWindow = 2 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "3"
action = { MoveWindow = 3 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "4"
action = { MoveWindow = 4 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "5"
action = { MoveWindow = 5 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "6"
action = { MoveWindow = 6 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "7"
action = { MoveWindow = 7 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "8"
action = { MoveWindow = 8 }
[[hotkeys]]
modifiers = "MOD|SHIFT"
key = "9"
action = { MoveWindow = 9 }

# media
[[hotkeys]]
modifiers = ""
key = "XF86_AudioRaiseVolume"
action = { Spawn = "/usr/bin/pactl set-sink-volume 0 +5%" }
[[hotkeys]]
modifiers = ""
key = "XF86_AudioLowerVolume"
action = { Spawn = "/usr/bin/pactl set-sink-volume 0 -5%" }
[[hotkeys]]
modifiers = ""
key = "XF86_AudioMute"
action = { Spawn = "/usr/bin/pactl set-sink-mute 0 toggle" }
[[hotkeys]]
modifiers = ""
key = "XF86_MonBrightnessUp"
action = { Spawn = "sudo light -A 5" }
[[hotkeys]]
modifiers = ""
key = "XF86_MonBrightnessDown"
action = { Spawn = "sudo light -U 5" }